version: '3.8'

services:
  tensorrt-llm-tritonserver:
    image: whisper-tensorrt-llm-tritonserver:0.0.0
  
    command: >
      bash -c "./launch_server.sh"
    ports:
      - 10200:10200
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
  # pytritonserver:
  #   image: nvcr.io/nvidia/pytorch:23.10-py3
  #   container_name: pytritonserver
  #   ports:
  #     - "8000:8000" # HTTP 서비스 포트
  #     - "8001:8001" # gRPC 서비스 포트
  #     - "8002:8002" # 메트릭스 서비스 포트
  #   volumes:
  #     - C:\Users\user\Documents\.cache:/models # 호스트의 './models' 디렉토리를 컨테이너의 '/models' 디렉토리에 마운트
  #   command: 
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #         - driver: nvidia
  #           capabilities: [gpu]