# for building tensorrt-llm
FROM nvidia/cuda:12.1.0-devel-ubuntu22.04

WORKDIR /workspace

ENV MPI_HOME=/usr/local/mpi
ENV PATH="$MPI_HOME/bin:$PATH"
ENV LD_LIBRARY_PATH="$MPI_HOME/lib:$LD_LIBRARY_PATH"


RUN apt-get update && apt-get -y install python3.10 python3-pip openmpi-bin libopenmpi-dev git

RUN pip install --upgrade pip setuptools wheel
RUN pip install tensorrt_llm -U --pre --extra-index-url https://pypi.nvidia.com
RUN git clone https://github.com/NVIDIA/TensorRT-LLM.git /workspace/TensorRT-LLM
WORKDIR /workspace/TensorRT-LLM
RUN pip install -r examples/whisper/requirements.txt

RUN apt-get update && \
    apt-get install -y git-lfs && \
    git lfs install


WORKDIR /workspace

COPY models /workspace/models
COPY assets /workspace/TensorRT-LLM/examples/whisper/assets


# For triton